'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _110216__cheesepuff__sad_song() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_110216__cheesepuff__sad_song", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property _325611__shadydave__my_love_piano_loop() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_325611__shadydave__my_love_piano_loop", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property _c() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_c", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property _e() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_e", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property _f() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_f", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property a() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("a", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property b() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("b", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property bb() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bb", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property c() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("c", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property d() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("d", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property eb() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("eb", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property f() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("f", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property g() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("g", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property g_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("g_", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Windows_Exclamation() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Exclamation", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
